server:
  port: ${PORT}
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-container/stockey?serverTimezone=Asia/Seoul
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.hibernate.SQL: debug


redis:
  lettuce:
    pool:
      max-active: 10
      max-idle: 10
      min-idle: 2
  port: 6379
  host: 'redis-container'
  password: 'ssafy'

# springdoc swagger
springdoc:
  api-docs:
    path: /docs # 접속 path 설정
  swagger-ui:
    path: /swagger-ui # 접속 path 설정


kakaoOauth:
  REST_API_KEY: ${KAKAO_KEY}
  REDIRECT_URL: ${KAKAO_REDIRECT_KEY}


jwt:
  # base64로 인코딩된 암호 키, HS512를 사용할 것이기 때문에, 512비트(64바이트) 이상이 되어야 합니다. 길게 써주세요
  secretKey: ${JWT_SECRET_KEY}
  access:
    expiration: 100
  refresh:
    expiration: 14400