interface Props {
  id: number
  name: string
}

const SampleStock: Props[] = [
  { id: 1, name: "SK이노베이션" },
  { id: 2, name: "S-Oil" },
  { id: 3, name: "HD현대" },
  { id: 4, name: "씨에스윈드" },
  { id: 5, name: "LG화학" },
  { id: 6, name: "POSCO홀딩스" },
  { id: 7, name: "포스코케미칼" },
  { id: 8, name: "고려아연" },
  { id: 9, name: "한화솔루션" },
  { id: 10, name: "롯데케미칼" },
  { id: 11, name: "현대제철" },
  { id: 12, name: "금호석유" },
  { id: 13, name: "SKC" },
  { id: 14, name: "코스모신소재" },
  { id: 15, name: "삼성물산" },
  { id: 16, name: "두산에너빌리티" },
  { id: 17, name: "삼성엔지니어링" },
  { id: 18, name: "한국조선해양" },
  { id: 19, name: "한화에어로스페이스" },
  { id: 20, name: "한국항공우주" },
  { id: 21, name: "삼성중공업" },
  { id: 75, name: "삼성전자" },
  { id: 2, name: "LG에너지솔루션" },
  { id: 3, name: "SK하이닉스" },
  { id: 4, name: "삼성바이오로직스" },
  { id: 6, name: "삼성SDI" },
  { id: 7, name: "삼성전자우" },
  { id: 32, name: "현대차" },
  { id: 9, name: "NAVER" },
  { id: 33, name: "기아" },
  { id: 12, name: "카카오" },
  { id: 13, name: "셀트리온" },
  { id: 34, name: "현대모비스" },
  { id: 17, name: "KB금융" },
  { id: 18, name: "LG전자" },
  { id: 19, name: "신한지주" },
  { id: 21, name: "LG" },
  { id: 22, name: "삼성생명" },
  { id: 23, name: "SK" },
  { id: 24, name: "하나금융지주" },
  { id: 25, name: "KT&G" },
  { id: 26, name: "카카오뱅크" },
  { id: 27, name: "삼성전기" },
  { id: 28, name: "한국전력" },
  { id: 31, name: "SK텔레콤" },
  { id: 32, name: "삼성화재" },
  { id: 26, name: "HMM" },
  { id: 34, name: "삼성에스디에스" },
  { id: 37, name: "LG생활건강" },
  { id: 25, name: "현대중공업" },
  { id: 27, name: "대한항공" },
  { id: 39, name: "엔씨소프트" },
  { id: 40, name: "우리금융지주" },
  { id: 41, name: "카카오페이" },
  { id: 43, name: "KT" },
  { id: 44, name: "크래프톤" },
  { id: 45, name: "기업은행" },
  { id: 47, name: "하이브" },
  { id: 48, name: "메리츠금융지주" },
  { id: 49, name: "아모레퍼시픽" },
  { id: 50, name: "LG이노텍" },
  { id: 29, name: "현대글로비스" },
  { id: 53, name: "KODEX 200" },
  { id: 54, name: "DB손해보험" },
  { id: 55, name: "오리온" },
  { id: 57, name: "SK스퀘어" },
  { id: 58, name: "SK바이오사이언스" },
  { id: 28, name: "맥쿼리인프라" },
  { id: 60, name: "LG디스플레이" },
  { id: 40, name: "F&F" },
  { id: 62, name: "넷마블" },
  { id: 64, name: "TIGER CD금리투자KIS(합성)" },
  { id: 65, name: "LG유플러스" },
  { id: 66, name: "CJ제일제당" },
  { id: 67, name: "SK바이오팜" },
  { id: 36, name: "한온시스템" },
  { id: 70, name: "SK아이이테크놀로지" },
  { id: 73, name: "한국타이어앤테크놀로지" },
  { id: 22, name: "현대건설" },
  { id: 77, name: "메리츠증권" },
  { id: 78, name: "유한양행" },
  { id: 42, name: "강원랜드" },
  { id: 23, name: "두산밥캣" },
  { id: 81, name: "미래에셋증권" },
  { id: 24, name: "포스코인터내셔널" },
  { id: 84, name: "GS" },
  { id: 39, name: "코웨이" },
  { id: 86, name: "현대차2우B" },
  { id: 87, name: "삼성카드" },
  { id: 88, name: "한미약품" },
  { id: 90, name: "현대오토에버" },
  { id: 92, name: "KODEX KOFR금리액티브(합성)" },
  { id: 31, name: "팬오션" },
  { id: 94, name: "현대해상" },
  { id: 95, name: "BGF리테일" },
  { id: 30, name: "한진칼" },
  { id: 97, name: "한국금융지주" },
  { id: 41, name: "아모레G" },
  { id: 43, name: "이마트" },
  { id: 100, name: "롯데지주" },
]

export default SampleStock
